config_version=2

solver(my_solver)=AMG
my_solver:algorithm=AGGREGATION
my_solver:selector=SIZE_2
my_solver:cycle=V
#my_solver:smoother(my_smoother)=MULTICOLOR_GS
my_solver:smoother(my_smoother)=MULTICOLOR_DILU
my_solver:postsweeps=1
my_solver:presweeps=0
my_solver:max_levels=100
my_solver:min_coarse_rows=2
my_solver:coarse_solver=DENSE_LU_SOLVER
my_solver:max_iters=1000000
my_solver:convergence=RELATIVE_INI_CORE
my_solver:tolerance=1e-12
my_solver:norm=L2
my_solver:print_grid_stats=1
my_solver:print_solve_stats=1
my_solver:monitor_residual=1
my_solver:obtain_timings=1

#my_smoother:relaxation_factor=1.0
#my_smoother:symmetric_GS=1
my_smoother:reorder_cols_by_color=1
my_smoother:insert_diag_while_reordering=1

#{
#    "config_version": 2, 
#    "solver": {
#        "selector": "SIZE_2",
#    }
#}
